# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 74fb66730046a827c9711b8973befbe3d5f1575f7e065bf0c807e036f17c1d749043e3127acb523af67f6d86c0255fba9d91c47c49660965112afe58589cf75d

test:
  secret_key_base: 6f3df3aa726c2e7a0d05f2dcd399733262391f0a12eacd928d5596b0ebc121a6e5b813c8dfdb30e2f8f017c5dace398dd20c4ec75d40d8c26b934feefc2431ac

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
